services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      DISK_SIZE: "100G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8005:8006
      - 3388:3389
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - $HOME/Documents/macos:/storage
      - $HOME/Documents/shared:/shared
    restart: always
    stop_grace_period: 2m
