services:
  windows:
    image: ${PRIVATE_REGISTRY}dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "yy"
      PASSWORD: "yy"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ~/windows:/storage
      - ~/Documents/Win11Win11_25H2_English_x64.iso:/boot.iso
    restart: always
    stop_grace_period: 2m